name: CD - Déploiement sur GitHub Pages

on:
 push:
  branches:["main"]
permissions:
contents: read
pages: white
id-token: white
jobs:
  Deploiement:
   runs-on: ubuntu-latest
   steps:
    - name: Récupération du code
     uses: actions/checkout@v3


    - name: Déploiement vers GitHub Pages
     uses: peaceiris/actions-gh-pages@v3
     with:
      github_toke: ${{secrets.GITHUB_TOKEN}}
      publish_dir 
